#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  BREWFILE="$HOME/.config/brew/Brewfile"
  if [ -f "$BREWFILE" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$BREWFILE"
  fi

fi
